#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# 既存のbash設定を読み込み
if [ -f $HOME/.bash_profile ]; then
  source  $HOME/.bash_profile
fi

# antigenはzshのプラグインマネージャー
if [ -f $HOME/antigen.zsh ]; then
  source $HOME/antigen.zsh
fi

# コンソールの他のタブや、他のウィンドウとコマンド入力履歴を共有
setopt share_history

# ヒストリ(履歴)を保存、数を増やす
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

# 直前と同じコマンドの場合は履歴に追加しない
setopt hist_ignore_dups

# 同じコマンドをヒストリに残さない
setopt hist_ignore_all_dups

# スペースから始まるコマンド行はヒストリに残さない
setopt hist_ignore_space

# コマンド履歴全取得
function history_all { history -E 1 }

# direnv
eval "$(direnv hook zsh)"
