#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# 既存のbash設定を読み込み
if [ -f "$HOME/.bash_profile" ]; then
  source  "$HOME/.bash_profile"
fi

# antigenはzshのプラグインマネージャー
if [ -f "$HOME/antigen.zsh" ]; then
  source "$HOME/antigen.zsh"
fi

# コンソールの他のタブや、他のウィンドウとコマンド入力履歴を共有
setopt share_history

# ヒストリ(履歴)を保存、数を増やす
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000

# 直前と同じコマンドの場合は履歴に追加しない
setopt hist_ignore_dups

# 同じコマンドをヒストリに残さない
setopt hist_ignore_all_dups

# スペースから始まるコマンド行はヒストリに残さない
setopt hist_ignore_space

# direnv
eval "$(direnv hook zsh)"

# 「/Users/motoi_komatsu/.zshrc:unalias:46: no such hash table element: mysql」というエラーが出ているので削除して良いかも
# See: https://github.com/ohmyzsh/ohmyzsh/issues/2283#issuecomment-45452691
# unalias mysql
