# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8==3.7.7]
      - id: pretty-format-json
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: sort-simple-yaml
      - id: check-yaml
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]

  - repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
      - id: black
        args: [--check]

  - repo: local
    hooks:
      # radon: Python tool that computes various metrics from the source code
      # See https://pypi.org/project/radon/

      # - Cyclomatic Complexity (CC).
      - id: radon cc
        name: radon cc
        entry: radon cc --show-complexity
        verbose: true
        language: python
        additional_dependencies: [radon]

      # - Maintainability Index.
      - id: radon mi
        name: radon mi
        entry: radon mi --show
        verbose: true
        language: python
        additional_dependencies: [radon]

      # - Raw metrics.
      - id: radon raw
        name: radon raw
        entry: radon raw
        verbose: true
        language: python
        additional_dependencies: [radon]

      # xenon: Monitoring tool based on Radon.
      # See See https://pypi.org/project/xenon/

      # - This will exit with a non-zero exit code
      - id: xenon
        name: xenon
        entry: xenon --max-absolute A --max-modules A --max-average A
        verbose: true
        language: python
        additional_dependencies: [xenon]

