name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: akiojin/auto-review-github-action@v0.2.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          target: "cs,yml"
          language: 日本語
