name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
